server:
  port: 8080
spring:
  liquibase:
    enabled: true
    change-log: liquibase-outputChangeLog.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_app
    username: postgres
    password: rootpass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect